[package]
name = "toledo"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4"
tiny_http = "0"
toml = "0"
serde_json = "1"
clap = {version = "4", features = ["derive"]}

[profile.release]
opt-level = 3
