GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`

GET http://localhost:8003/
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`

GET http://localhost:8003#test
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`

GET http://localhost:8003/#test
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Dados passado pela porta serial corrompidos.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`A balança está em movimento.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Peso acima do limite da balança.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Unidade da pesagem está incorreta.`
