GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`

GET http://localhost:8003/
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`

GET http://localhost:8003#test
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`

GET http://localhost:8003/#test
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Data passed through the serial port is corrupt.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`The scale is moving.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weight above the scale limit.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`

GET http://localhost:8003
HTTP 500
Content-Type: text/plain; charset=UTF-8
`Weighing unit is incorrect.`
